export default {
    txtberanda: "//h2[contains(@class,'text-[40px] font-extrabold leading-normal sm:text-5xl/normal xl:text-6xl/normal')]",
    btnburger: "//button[contains(@class,'pr-6 lg:hidden')]",
    btnhubungikami: "//span[contains(text(),'Hubungi Kami')]",
    linkwa: "https://api.whatsapp.com/send/?phone=628119735575&text=Halo%20Kanggo%2C%0A%0ASaya%20ingin%20mengetahui%20info%20lebih%20lanjut%20tukang%20Kanggo%2C%20bisa%20dibantu%3F%20%0a%0aTautan:%20https://www.kanggo.id%0a%0aTerima%20kasih&type=phone_number&app_absent=0",
    btncekberitalain: "//span[contains(text(),'Cek Berita Lain')]",
    btndownloadqr: "//button[contains(text(),'Download dengan QR Code')]",
    imgqr: "//img[contains(@alt,'QR Code')]",
    txttentangkami: "//a[contains(text(),'Tentang Kami')]",
    txtberita: "//a[contains(text(),'Berita')]",
    txtblog: "//a[contains(text(),'Blog')]",
    txtkarir: "//a[contains(text(),'Karir')]",
    txtperbaikibangunan: "//button[contains(text(),'Perbaiki Bangunan')]",
    txtuntukkonsumen: "//span[contains(text(),'Untuk Konsumen')]",
    txtuntukperusahaan: "//span[contains(text(),'Untuk Perusahaan')]",
    txtuntuktukangjagoan: "//span[contains(text(),'Untuk Tukang Jagoan')]",
    txtuntukpengembang: "//span[contains(text(),'Untuk Pengembang')]",
    txtciptakanpekerjaan: "//a[contains(text(),'Ciptakan Pekerjaan')]",
    txtinilahkanggo: "//a[contains(text(),'Inilah Kanggo')]",
}